version: "2"
services:
  mittwald_shopware_shop:
    container_name: mittwald_schulung_shop
    image: mittwald/shopware:latest
    #restart: always
    links:
      - mittwald_shopware_db:db
      - mittwald_shopware_mailcatcher:smtp
    volumes:
      - ./Volumes/Shop/Config/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      VIRTUAL_HOST: www.mittwald-shopware.dev
    volumes_from:
      - container:data-sync-mittwald:rw

  mittwald_shopware_db:
    container_name: mittwald_schulung_db
    image: mysql:5.7
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopware
      MYSQL_USER: swuser
      MYSQL_PASSWORD: swpassword
    volumes:
      - ./Volumes/Db/:/var/lib/mysql

  mittwald_shopware_nginx_proxy:
    container_name: mittwald_shopware_nginx_proxy
    #restart: always
    image: jwilder/nginx-proxy:latest
    ports:
      - 8080:80
      - 8043:443
      - 8088:1080
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mittwald_shopware_phpmyadmin:
    container_name: mittwald_shopware_phpmyadmin
    #restart: always
    image: phpmyadmin/phpmyadmin
    links:
      - mittwald_shopware_db:db
    environment:
      VIRTUAL_HOST: db.mittwald-shopware.dev

  mittwald_shopware_mailcatcher:
    image: hinshun/mailcatcher
    environment:
      VIRTUAL_HOST: mail.mittwald-shopware.dev
    ports:
      - 1080:1080 

volumes:
  data-sync-mittwald:
    external: true

